name: Unity GameCI

on: [push, pull_request]

jobs:
  build:
    name: Build Android Project
    runs-on: ubuntu-latest
    steps:    
      - uses: jlumbroso/free-disk-space@v1.3.1
      
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          androidExportType: 'androidAppBundle'
          unityVersion: 2021.3.11f1
          androidKeystoreName: springman # This file won't exist, but this property needs to exist.
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

      - name: Convert aab to apk
        id: convert_aab
        uses: mukeshsolanki/bundletool-action@v1.0.0
        with:
          aabFile: build/Android/Android.aab
          base64Keystore: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keystorePassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          keystoreAlias: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          keyPassword: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          apkPath: build/Android/Springman-Universal.apk

      - uses: actions/upload-artifact@v4
        with:
          name: springman-universal
          path: ${{ steps.convert_aab.outputs.apkPath }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/Android/Springman-Universal.apk
